export default {
  activeHeart: require("./../assets/image/activeHeart.png"),
  marker: require("./../assets/image/marker.png"),
  logo: require("./../assets/image/logo.png"),
  inActiveHeart: require("./../assets/image/inActiveHeart.png"),
  ic_usrr_1: require("./../assets/image/ic_usrr_1.png"),
  ic_srch: require("./../assets/image/ic_srch.png"),
  ic_user: require("./../assets/image/ic_user.png"),
  ic_red_home: require("./../assets/image/ic_red_home.png"),
  ic_red_add: require("./../assets/image/ic_red_add.png"),
  ic_plus: require("./../assets/image/ic_plus.png"),
  ic_notify: require("./../assets/image/ic_notify.png"),
  ic_main_logo: require("./../assets/image/ic_main_logo.png"),
  ic_logout: require("./../assets/image/ic_logout.png"),
  ic_loc: require("./../assets/image/ic_loc.png"),
  ic_key: require("./../assets/image/ic_key.png"),
  ic_home: require("./../assets/image/ic_home.png"),
  ic_home_icon: require("./../assets/image/ic_home_icon.png"),
  ic_grey_tick: require("./../assets/image/ic_grey_tick.png"),
  ic_google: require("./../assets/image/ic_google.png"),
  ic_flag: require("./../assets/image/ic_flag.png"),
  ic_facebook: require("./../assets/image/ic_facebook.png"),
  ic_edit: require("./../assets/image/ic_edit.png"),
  ic_down: require("./../assets/image/ic_down.png"),
  ic_dots: require("./../assets/image/ic_dots.png"),
  ic_direction: require("./../assets/image/ic_direction.png"),
  ic_crss: require("./../assets/image/ic_crss.png"),
  ic_cross: require("./../assets/image/ic_cross.png"),
  ic_blue_tick: require("./../assets/image/ic_blue_tick.png"),
  ic_blue_setting: require("./../assets/image/ic_blue_setting.png"),
  ic_back_arrow: require("./../assets/image/ic_back_arrow.png"),
  ic_add: require("./../assets/image/ic_add.png"),
  ic_1: require("./../assets/image/ic_1.png"),
  ic_apple:require("./../assets/image/ic_apple.png"),
};
