export default {
  TUTORIAL: "Tutorial",
  LOGIN: "Login",
  SELECTLOCATIOM: "SetlectLocation",
  SPLASH: "Splash",
  APPLOGIN: "AppLogin",
  SETPASSWORD: "SetPassword",
  SIGNUP: "Signup",
  SIGNUPOTP: "SignupOtp",
  HOME: "Home",
  VIEWMAP: "ViewMap",
  TABSROUTES: "TabRoutes",
  NOTIFICATION: "Notification",
  APPPROFILE: "APPPROFILE",
  SEARCHLOCATION: "SearchLocation",
  GALLARY: "Gallary",
  EDITPROFILE: "Edit Profile",
  CHANGEPASSWORD: "ChnagePassword",
};
